// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using qlsinhvien.Context;

#nullable disable

namespace qlsinhvien.Migrations
{
    [DbContext(typeof(AppQLSVContext))]
    [Migration("20230804034129_qlsinhvien")]
    partial class qlsinhvien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("qlsinhvien.Entities.DiemSinhVien", b =>
                {
                    b.Property<int>("MaLopMonHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaSinhVien")
                        .HasColumnType("int");

                    b.Property<float>("DiemChuyenCan")
                        .HasColumnType("real");

                    b.Property<float>("DiemCuoiKi")
                        .HasColumnType("real");

                    b.Property<float>("DiemGiuaKi")
                        .HasColumnType("real");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HocKi")
                        .HasColumnType("int");

                    b.HasKey("MaLopMonHoc", "MaSinhVien");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("DiemSinhVien");
                });

            modelBuilder.Entity("qlsinhvien.Entities.GiangVien", b =>
                {
                    b.Property<int>("MaGiangVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiangVien"));

                    b.Property<string>("DiaChiThuongTru")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaGiangVien");

                    b.ToTable("GiangVien");
                });

            modelBuilder.Entity("qlsinhvien.Entities.Khoa", b =>
                {
                    b.Property<int>("MaKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoa"));

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("qlsinhvien.Entities.KhoaMonHoc", b =>
                {
                    b.Property<int>("MaKhoa")
                        .HasColumnType("int");

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("int");

                    b.HasKey("MaKhoa", "MaMonHoc");

                    b.HasIndex("MaMonHoc");

                    b.ToTable("Khoa-MonHoc");
                });

            modelBuilder.Entity("qlsinhvien.Entities.LopMonHoc", b =>
                {
                    b.Property<int>("MaLopMonHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLopMonHoc"));

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int");

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("int");

                    b.Property<string>("TenLopMonHoc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaLopMonHoc");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaMonHoc");

                    b.ToTable("LopMonHoc");
                });

            modelBuilder.Entity("qlsinhvien.Entities.LopQuanLi", b =>
                {
                    b.Property<int>("MaLopQuanLi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLopQuanLi"));

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int");

                    b.Property<int>("MaKhoa")
                        .HasColumnType("int");

                    b.Property<string>("TenLopQuanLi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaLopQuanLi");

                    b.HasIndex("MaGiangVien")
                        .IsUnique();

                    b.HasIndex("MaKhoa");

                    b.ToTable("LopQuanLi");
                });

            modelBuilder.Entity("qlsinhvien.Entities.MonHoc", b =>
                {
                    b.Property<int>("MaMonHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMonHoc"));

                    b.Property<bool>("BatBuoc")
                        .HasColumnType("bit");

                    b.Property<int?>("MaMonTienQuyet")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("SoTinChi")
                        .HasColumnType("tinyint");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("MaMonHoc");

                    b.HasIndex("MaMonTienQuyet");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("qlsinhvien.Entities.SinhVien", b =>
                {
                    b.Property<int>("MaSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSinhVien"));

                    b.Property<string>("DiaChiThuongTru")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("MaLopQuanLi")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoTruong")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaSinhVien");

                    b.HasIndex("MaLopQuanLi");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("qlsinhvien.Entities.DiemSinhVien", b =>
                {
                    b.HasOne("qlsinhvien.Entities.LopMonHoc", "LopMonHoc")
                        .WithMany()
                        .HasForeignKey("MaLopMonHoc")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("qlsinhvien.Entities.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LopMonHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("qlsinhvien.Entities.KhoaMonHoc", b =>
                {
                    b.HasOne("qlsinhvien.Entities.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("qlsinhvien.Entities.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("qlsinhvien.Entities.LopMonHoc", b =>
                {
                    b.HasOne("qlsinhvien.Entities.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("qlsinhvien.Entities.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("qlsinhvien.Entities.LopQuanLi", b =>
                {
                    b.HasOne("qlsinhvien.Entities.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("qlsinhvien.Entities.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("qlsinhvien.Entities.MonHoc", b =>
                {
                    b.HasOne("qlsinhvien.Entities.MonHoc", "MonTienQuyet")
                        .WithMany()
                        .HasForeignKey("MaMonTienQuyet")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("MonTienQuyet");
                });

            modelBuilder.Entity("qlsinhvien.Entities.SinhVien", b =>
                {
                    b.HasOne("qlsinhvien.Entities.LopQuanLi", "LopQuanLi")
                        .WithMany()
                        .HasForeignKey("MaLopQuanLi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopQuanLi");
                });
#pragma warning restore 612, 618
        }
    }
}
