using EnumStringValues;

namespace qlsinhvien.Entities;

public enum EQuyen
{
    [StringValue("xemtatca-bomon")]
    XemTatCa_BOMON,
    [StringValue("xemtatca-khoa")]
    XemTatCa_KHOA,
    [StringValue("xemtatca-giangvien")]
    XemTatCa_GIANGVIEN,
    [StringValue("xemtatca-sinhvien")]
    XemTatCa_SINHVIEN,
    [StringValue("xemtatca-lopmonhoc")]
    XemTatCa_LOPMONHOC,
    [StringValue("xemtatca-monhoc")]
    XemTatCa_MONHOC,
    [StringValue("xemtatca-lopquanli")]
    XemTatCa_LOPQUANLI,
    [StringValue("xemtatca-vaitro")]
    XemTatCa_VAITRO,
    [StringValue("xemtatca-quyen")]
    XemTatCa_QUYEN,
    [StringValue("xemtatca-nguoidung")]
    XemTatCa_NGUOIDUNG,
    [StringValue("xemtheoma-sinhvien")]
    XemTheoMa_SINHVIEN,
    [StringValue("xemtheoma-giangvien")]
    XemTheoMa_GIANGVIEN,
    [StringValue("xemtheoma-bomon")]
    XemTheoMa_BOMON,
    [StringValue("xemtheoma-khoa")]
    XemTheoMa_KHOA,
    [StringValue("xemtheoma-lopmonhoc")]
    XemTheoMa_LOPMONHOC,
    [StringValue("xemtheoma-monhoc")]
    XemTheoMa_MONHOC,
    [StringValue("xemtheoma-lopquanli")]
    XemTheoMa_LOPQUANLI,
    [StringValue("xembanthan-sinhvien")]
    XemBanThan_SINHVIEN,
    [StringValue("xembanthan-giangvien")]
    XemBanThan_GIANGVIEN,
    [StringValue("capquyen-taikhoan")]
    CapQuyen_TAIKHOAN,
    [StringValue("them-sinhvien")]
    Them_SINHVIEN,
    [StringValue("capnhat-sinhvien-lopquanli")]
    CapNhat_SINHVIEN_LOPQUANLI,
    [StringValue("capnhat-sinhvien-lopmonhoc")]
    CapNhat_SINHVIEN_LOPMONHOC,
    [StringValue("capnhat-giangvien-lopquanli")]
    CapNhat_GIANGVIEN_LOPQUANLI,
    [StringValue("capnhat-giangvien-lopmonhoc")]
    CapNhat_GIANGVIEN_LOPMONHOC,
    [StringValue("them-nguoidung-sinhvien")]
    Them_NGUOIDUNG_SINHVIEN,
    [StringValue("them-nguoidung-giangvien")]
    Them_NGUOIDUNG_GIANGVIEN
}